# Generated by Django 4.0.4 on 2022-05-13 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngresarInfoMatricula',
        ),
    ]
